### ISSUE TITLE
Spelling of the ggmsa argument "posHighligthed"

### ISSUE THREAD

**Issue by takosa** [YuLab-SMU/ggmsa#29]
Hi, I found a typo in a argument of ggmsa function "posHighlig**th**ed" and I think it is better to change its case style from came case to snake case because the other arguments is snake case.

**Comment by nyzhoulang** [comment]
Hi, @takosa 

Thanks for your feedback.
I fixed it in ggmsa devel ver 1.1.3 

Regards,
Lang
