### ISSUE TITLE
Required R version too new

### ISSUE THREAD

**Issue by iferres** [YuLab-SMU/ggmsa#31]
Hi, I have a question related to the required R version:
https://github.com/YuLab-SMU/ggmsa/blob/2edbad94baeb72999a741f68d30a028f9160871b/DESCRIPTION#L15
Is it really needed to have this very new R version? I'm asking because I'm working on a system which only has R 4.0.5, being the newer available yet on the OS repositories. 
I get the following error:
```
ERROR: this R is version 4.0.5, package 'ggmsa' requires R >= 4.1.0
```
If it isn't strictly necessary, may be it could make the package available to more people to have an older R version to depend on.
Thank you for the package, anyway!

**Comment by GuangchuangYu** [comment]
Bioconductor is bound with a particular R version, and this is required by the Bioconductor policy.
