### ISSUE TITLE
geom_msaBar conservation layer incorrectly aligned

### ISSUE THREAD

**Issue by tgstoecker** [YuLab-SMU/ggmsa#34]
geom_msaBar() leads to a misaligned (too narrow) conservation layer:  
Example code from here - [http://yulab-smu.top/ggmsa/reference/geom_msaBar.html](http://yulab-smu.top/ggmsa/reference/geom_msaBar.html):
```
f <- [system.file](https://rdrr.io/r/base/system.file.html)("extdata/sample.fasta", package="ggmsa")
[ggmsa](http://yulab-smu.top/ggmsa/reference/ggmsa.html)(f, 221, 280, font = NULL, seq_name = TRUE) + geom_msaBar()
```
<img width="728" alt="geom_msaBar_misaligned" src="https://user-images.githubusercontent.com/53227400/167137160-209aceb6-7227-4dcf-9936-065702a72cf3.png">

I have played around with the graphical output settings both in rstudio and jupyter but nothing seems to help.  
Am I missing sth. obvious?

**Comment by nyzhoulang** [comment]
Hi, @tgstoecker 
    
Sorry for the late reply.

I have updated the aligned method for  `geom_msaBar`. Now, the conservation layer can align with Stacked MSA correctly.
You can try again in the latest development release (ggmsa v1.3.2).

```
devtools::install_github("YuLab-SMU/ggmsa")
f <- system.file("extdata/sample.fasta", package="ggmsa")
ggmsa(f, 221, 280,  font = NULL, seq_name = TRUE) + geom_msaBar()
```
![Rplot](https://user-images.githubusercontent.com/46915370/168295817-dcf40a42-b667-4aba-bd5d-c24bdbae73f9.png)

Regards,
Lang
