### ISSUE TITLE
Commented out examples in documentation of `ggmsa()`?

### ISSUE THREAD

**Issue by ramiromagno** [YuLab-SMU/ggmsa#39]
Part of the examples in doc of `ggmsa()` are commented out:

https://github.com/YuLab-SMU/ggmsa/blob/9a6ef7d06651a115399fec84e88112d999c79060/R/ggmsa.R#L64-L74

You could make them work if you:

```
#XMultipleAlignment objects can be used as input in the 'ggmsa'
AAMultipleAlignment <- Biostrings::readAAMultipleAlignment(fasta)
ggmsa(AAMultipleAlignment, 164, 213, color="Chemistry_AA")

#XStringSet objects can be used as input in the 'ggmsa'
AAStringSet <- Biostrings::readAAStringSet(fasta)
ggmsa(AAStringSet, 164, 213, color="Chemistry_AA")

#Xbin objects from 'seqmagick' can be used as input in the 'ggmsa'
AAbin <- seqmagick::fa_read(fasta)
ggmsa(AAbin, 164, 213, color="Chemistry_AA")
```

Otherwise you leave the user wondering if those examples are to be used or not...

**Comment by nyzhoulang** [comment]
We just want users to know that `ggmsa` can have different input objects, but it doesn't have to be actually run. This creates unnecessary example runtime.

**Comment by ramiromagno** [comment]
Then you could perhaps mark it with `\dontrun{}`: https://r-pkgs.org/man.html?q=donttest#man-functions.

And then again, functions `readAAStringSet()` and `fa_read()` would work best if rewritten to `Biostrings::readAAStringSet()` and `seqmagick::fa_read()`.

**Comment by nyzhoulang** [comment]
> Then you could perhaps mark it with `\dontrun{}`: https://r-pkgs.org/man.html?q=donttest#man-functions.
> 
> And then again, functions `readAAStringSet()` and `fa_read()` would work best if rewritten to `Biostrings::readAAStringSet()` and `seqmagick::fa_read()`.

That's excellent advice. I updated the examples in `ggmsa()`. 
Thanks!

**Comment by ramiromagno** [comment]
Thanks for the quick turnover. But I still think you should use `Biostrings::readAAStringSet()` and `seqmagick::fa_read()` --- notice the name of the package prepended.

**Comment by nyzhoulang** [comment]
![image](https://user-images.githubusercontent.com/46915370/168709244-3bd81097-8297-4762-94f4-eb01ae2589d0.png)

I'm sure used the `Biostrings: : readAAStringSet ()` and `seqmagick: : fa_read ()`.
There may be latency on the network.

**Comment by ramiromagno** [comment]
Okay, sorry. I had a look at a commit before the last one... that's why I thought you didn't. I should had looked better :)

Once again, thank you for the fast reply.
