### ISSUE TITLE
cannot read fasta alignment file

### ISSUE THREAD

**Issue by wowfee** [YuLab-SMU/ggmsa#45]
Hello, After ggmsa is installed successfully, I read in the sequence using the following code:
```
library(ggmsa)
protein_sequences <- system.file("extdata","test.fasta",package="ggmsa")
```
nor errors,but i think it not read fasta file,cause :
`protein_sequences
[1]""
`
nothings in protein_sequences, and my fasta file format is :
```
>AF178440.1/5925-6123
UUGACUAUGUGAUCUUGCUUUCG...
>AB017037.1/6286-6484
GAAAAUGUGUGAUCUGAUUAGAA...
>AF014388.1/6078-6278
GUUAAGAUGUGAUCUUGCUUCCU...
>AF218039.1/6028-6228
GCAAAAAUGUGAUCUUGCUUGUA...
>AF183905.1/5647-5848
CCAACAAUGUGAUCUUGCUUGCG...
>AB006531.1/6003-6204
CUGACUAUGUGAUCUUAUUAAAA...
>AF022937.1/6935-7121
AGUGUUGUGUGAUCUUGCGCGAU...
```
all sequences are alingment and have same length. i wonder to know if there are any problem above ? 
thanks

**Comment by orangeSi** [comment]
```protein_sequences <- system.file("extdata","test.fasta",package="ggmsa")```  mean ``` ggmsa_install_path/extdata/test.fasta```, so  can also set fasta path by  ``` protein_sequences <- "/xxx/xxx/test.fasta"```.
That confuse me a lot for R  newbie!

**Comment by nicolo-tellini** [comment]
Hello, 

I have the same issue can you explain what is the correct way to upload a fasta ?

thanks 

nic
