### ISSUE TITLE
Re-list ggmsa on CRAN

### ISSUE THREAD

**Issue by ababaian** [YuLab-SMU/ggmsa#58]
Hello, I'd like to say lovely package!

I'm a developer of [`palmID`](https://github.com/ababaian/palmid) and I would like to add `ggmsa` as a dependency to our virus analysis package. Currently `ggmsa` is listed as "archived" on the CRAN R archive (https://cran.r-project.org/web/packages/ggmsa/index.html). Is there a possibility of getting `ggmsa` relisted into CRAN there so it's easier to integrate your package as a dependency?

Cheers

**Comment by nyzhoulang** [comment]
Hi, Artem

Regrettably, `ggmsa`did not pass the check during the upload to CRAN, and the issues identified by CRAN are proving challenging to address. As a result, we have decided against releasing it on CRAN.

Sincerely,
Lang

**Comment by GuangchuangYu** [comment]
@ababaian The ggmsa package is released within the Bioconductor project, see <https://bioconductor.org/packages/release/bioc/html/ggmsa.html>. It is OK to add ggmsa as a dependency and submit your package to cran.

**Comment by ababaian** [comment]
I did find a work-around, I'm not 100% certain it will pass CRAN checks itself but for the sake of documentation the solution is in the package `DESCRIPTION` file:

```
...
Imports:
    dbplyr,
    downloadthis,
    ...
    ggmsa
    ...

````

and then you have to add a `Remotes` section to `DESCRIPTION` which looks like

```
Remotes:
    bioc::release/ggmsa
```

This seems to work at the moment. Shame about the difficulty of getting `ggtree/ggmsa` into CRAN but also understandable. Thanks for the help.
