### ISSUE TITLE
Tree + Seq Logo & AA one-letter code on sequence

### ISSUE THREAD

**Issue by alptaciroglu** [YuLab-SMU/ggmsa#7]
Thanks for this great package!

I was wondering about the implementation of two things on module **ggtree(tree) + geom_facet()**:

Sequence logo on top of MSA?
AA one-letter code at sequences on MSA? 

Best

**Comment by nyzhoulang** [comment]
Hi, alptacirogu,

Tanks for your message. 

> Sequence logo on top of MSA?
AA one-letter code at sequences on MSA?

We have implemented this feature in the latest development version of ggmsa.
For example:
```
library(Biostrings)
library(ape)
library(ggtree)
protein_sequences <- system.file("extdata", "sample.fasta", package = "ggmsa")
x <- readAAStringSet(protein_sequences)
d <- as.dist(stringDist(x, method = "hamming")/width(x)[1])
tree <- bionj(d)
p <- ggtree(tree ) + geom_tiplab()

data = tidy_msa(x, 180, 208)
p + geom_facet(geom = geom_msa, data = data,  panel = 'msa', font = NULL, color = "Chemistry_AA") + 
    geom_facet(geom = ggmsa:::geom_logo, data = data,  panel = 'msa', color = "Chemistry_AA", adaptive = T) + 
      xlim_tree(1)
```
![12](https://user-images.githubusercontent.com/46915370/91676412-4edb1080-eb72-11ea-85ee-7460e951123b.png)

Now, module **ggtree(tree) + geom_facet(geom_msa) + geom_facet(geom_logo)** can be used very easily.

**Comment by alptaciroglu** [comment]
Thanks a lot for the work!

I was unable to install the dev version of ggmsa though.. 

![image](https://user-images.githubusercontent.com/13270606/91728367-a9dd2980-ebab-11ea-9f80-cb5c8e34730e.png)

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      pillar_1.4.6      compiler_3.6.1    remotes_2.1.1     prettyunits_1.1.1 tools_3.6.1       testthat_2.3.2   
 [8] digest_0.6.25     pkgbuild_1.1.0    pkgload_1.1.0     memoise_1.1.0     lifecycle_0.2.0   gtable_0.3.0      nlme_3.1-147     
[15] lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.7       cli_2.0.2         rstudioapi_0.11   curl_4.3          parallel_3.6.1   
[22] withr_2.2.0       fs_1.4.1          desc_1.2.0        devtools_2.3.0    rprojroot_1.3-2   grid_3.6.1        glue_1.4.2       
[29] R6_2.4.1          processx_3.4.3    fansi_0.4.1       sessioninfo_1.1.1 callr_3.4.3       magrittr_1.5      usethis_1.6.1    
[36] scales_1.1.1      backports_1.1.9   ps_1.3.4          ellipsis_0.3.1    assertthat_0.2.1  ape_5.3           colorspace_1.4-1 
[43] munsell_0.5.0     crayon_1.3.4     
```

**Comment by nyzhoulang** [comment]
This may be caused by some Chinese annotations in **seqlogo.R**  , I have deleted them.

**Comment by alptaciroglu** [comment]
Thanks a lot again!

I was able to generate sequence logo at the top of the msa panel with your code. Though I am getting some filled ambiguous squares in the sequence logo. More apparent if the phylogenetic tree is larger. Could you take a look?

![image](https://user-images.githubusercontent.com/13270606/91885125-eb470500-ec8f-11ea-91c7-7b910981ab6c.png)
![image](https://user-images.githubusercontent.com/13270606/91885316-411bad00-ec90-11ea-831c-eb7b89b16085.png)

**Comment by nyzhoulang** [comment]
**1.** 
> Though I am getting some filled ambiguous squares in the sequence logo. 

It looks like the LETTER **“I”** in _helvetical_ font(Default) rather than an incorrect code, and you can use _DroidSansMono_ font to solve this problem.
```
protein_sequences <- system.file("extdata", "sample.fasta", package = "ggmsa")

ggmsa(protein_sequences, color = "Chemistry_AA", 165, 236, seq_name = F, font = "DroidSansMono", char_width = 0.5) + 
    geom_seqlogo(color = "Chemistry_AA", font = "helvetical", adaptive = F )+ theme_void()

ggmsa(protein_sequences, color = "Chemistry_AA", 165, 236, seq_name = F, font = "DroidSansMono", char_width = 0.5) + 
    geom_seqlogo(color = "Chemistry_AA", font = "DroidSansMono", adaptive = F ) + theme_void()
```
![logo11](https://user-images.githubusercontent.com/46915370/91929076-30ab1700-ed10-11ea-9ee1-5b9300acfcee.png)
![logo2](https://user-images.githubusercontent.com/46915370/91929085-356fcb00-ed10-11ea-8d96-a89d0167b2f3.png)

PS: Using  `available_fonts()` to check out that Font Families currently available.
![image](https://user-images.githubusercontent.com/46915370/91928434-98f8f900-ed0e-11ea-8b24-344ee282d042.png)

**2.**
> More apparent if the phylogenetic tree is larger

This is caused by the `adaptive` parameter:  _A logical value indicating whether the overall height of seqlogo corresponds to the number of sequences.  If FALSE, seqlogo overall height = 4 fixedly_.

**So, you can try ggtree(tree) + geom_facet(geom_msa) + geom_facet(geom_logo, font = "DroidSansMono",  adaptive = F ) **

**Comment by alptaciroglu** [comment]
Perfect! Thanks a lot

**Comment by alptaciroglu** [comment]
Hello again, 

I switched to `msaplot` function from `p + geom_facet()` after some updates to my code. 

Following code generates plot below: 
`msaplot(p = tree, bg_line = T, fasta = msaFastaName, offset = 7.5, window = c(1,50)) `

![image](https://user-images.githubusercontent.com/13270606/124656351-c1f79680-dea9-11eb-9451-aecb714466fa.png)

What I want is a plot like below:
![DesiredPlot](https://user-images.githubusercontent.com/13270606/124656849-6679d880-deaa-11eb-826a-85a1d4218987.png)

Can this be done? Thanks in advance.

**Comment by nyzhoulang** [comment]
Hi @alptaciroglu, 

The`msaplot` function is the predecessor of `ggmsa` package.  We developed  `ggmsa` as an extension of `msaplot`. So, the use of `msaplot` for visualizing sequence alignments is limited.

 The example of `tree + seq+ logo` can not be achieved in `msaplot`. Currently, the plot could be done only by `p + gemo_facet(geom_msa)  + geom_facet(geom_logo)`.

Best,
Lang

**Comment by alptaciroglu** [comment]
Got it, thanks a lot!

**Comment by cms72** [comment]
Hi - Is there a way to do this but using geom_msaBar instead of geom_logo? Thanks!
