### ISSUE TITLE
能否支持任意字母？

### ISSUE THREAD

**Issue by ShixiangWang** [YuLab-SMU/ggmsa#8]
Y 叔你好，

我有需要做多序列比对和可视化，但我的序列并不是蛋白的，这个可视化能否拓展到任意字母 A-Z？我目前看到 J、O、X、Z是不支持的

![image](https://user-images.githubusercontent.com/25057508/90229051-da059800-de49-11ea-856b-28fdc89eaeb7.png)

**Comment by nyzhoulang** [comment]
你好,Shixiang,

在最新的ggmsa开发版中，我们已经将所有字母补充完整，感谢你提供的意见。

祝好。

**Comment by ShixiangWang** [comment]
非常感谢。
